### PR TITLE
Transforming the sample into a multi step tutorial

### PR DESCRIPTION
**Pull request by jmprieur**
Transforming the sample into a multi step tutorial

To review this PR, it's better to look at the individual commits:
- [e504c70](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/pull/96/commits/e504c7084d22eef03e24f05446e762ddc89bb1d0) is pretty mechanical. It's about moving the current content of the repo to the fist sub-folder "1-Basic", and the content of https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/jennyf/iosBroker to a second folder "2-With-broker". It also overrides the README.md which was in jennyf/iosBroker with this one: [jennyf/ios - README.md](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/jennyf/ios/XamarinBroker/UserDetailsClientBroker/README.md), which was from a different branch
  There are a lot of file changes, but nothing to review specifically, this is pertty mechanical
- [8b10429](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/pull/96/commits/8b1042929b074f03e873b1a5a99037d146d73753):
  - Adds a README.md for the repo, pointing to the sub folders
  - Adds build.bat and BuildAllSln.proj files to build the whole sample locally
  - Updates the sub folders readme files.

### CODE REVIEW

**Comment by jennyf19** [comment]
>                                                   -ReplyUrls "urn:ietf:wg:oauth:2.0:oob" `

this reply url will not work here.

---
Refers to: 1-Basic/AppCreationScripts/Configure.ps1:155 in a157dad. [](commit_id = a157dad95f0ffd10b10a1355e96fa8d7af14aae6, deletion_comment = False)

**Comment by jennyf19** [comment]
>    $replyUrlForApp = "msal"+$clientAadApplication.AppId+"://auth"

does this also get put into the android manifest?

---
Refers to: 1-Basic/AppCreationScripts/Configure.ps1:158 in a157dad. [](commit_id = a157dad95f0ffd10b10a1355e96fa8d7af14aae6, deletion_comment = False)

**Comment by jmprieur** [comment]
no it does not, but should.

**Comment by jennyf19** [comment]
so the manifest now gets updated for broker? @jmprieur

**Pull request merged**
