### PR TITLE
Android text updates

### PR DESCRIPTION
**Pull request by aiwangmicrosoft**

### CODE REVIEW

**Comment by aiwangmicrosoft** [comment]
@jmprieur and @trwalke can I get your eyes on the readme update for 2-with broker? 

For step 4g, what is the file name of the manifest? Maybe it's not obvious to me only?

**Comment by jmprieur** [comment]
@aiwangmicrosoft : the manifest is the AndroidManifest: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/94e7513a67e87197db14ba9691bb45b2c69035f2/2-With-broker/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml

Note that there is an intent filter in the 1-Basic folder. 

https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/94e7513a67e87197db14ba9691bb45b2c69035f2/1-Basic/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml#L9-L14

@tawalke : should we do the same in 2-With-broker ?

**Comment by bgavrilMS** [comment]
@aiwangmicrosoft - don't hesitate to merge once PR is approved.

**Comment by trwalke** [comment]
@jmprieur yes, intent filter update here.
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/pull/141

**Pull request merged**
