### PR TITLE
Updating the InterntFilter in MsalActivity according to the ClientId …

### PR DESCRIPTION
**Pull request by jmprieur**
Updating the InterntFilter in MsalActivity according to the ClientId which is used
Also related to #127, probably

### CODE REVIEW

**Comment by jmprieur** [comment]
@trwalke : as explained in the Teams Channel

**Comment by TiagoBrenck** [comment]
@jmprieur this change is on master branch already: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/pull/120

**Comment by jmprieur** [comment]
@jennyf19 @trwalke @aiwangmicrosoft ?

**Comment by jennyf19** [comment]
@jmprieur this can be closed correct?

**Comment by jmprieur** [comment]
@jennyf19, I don't think so? the client ID seems different?

**Comment by jennyf19** [comment]
@jmprieur it's already been merged in. so i was asking for closing this PR, not merging. :)

**Comment by jennyf19** [comment]
already fixed.

**Pull request closed without merging**
